//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : System Obsługi Studiów
//  @ File Name : Course.h
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#if !defined(_COURSE_H)
#define _COURSE_H

// Deklaracja zależności i bibliotek
#include <string>
#include <vector>
#include "Student.h"
#include "Lecturer.h"
#include "Material.h"
#include "VideoConference.h"

// Deklaracja klas
class Lecturer;
class Student;
class VideoConference;

// Deklaracja klasy Course
class Course {
public:
	Course(std::string name, Lecturer * lecturer);  // Konstruktor klasy Course przyjmujący nazwę kursu i wykładowcę prowadzącego kurs
    Course(std::string name, Lecturer * lecturer, std::string isVideoConferenceCreated);  // Konstruktor klasy Course przyjmujący nazwę kursu, wykładowcę prowadzącego kurs i informację o tym, czy wideokonferencja została utworzona
    std::string getName();  // Akcesor pola name
    void setName(std::string name);  // Mutator pola name
    Lecturer * getLecturer();  // Akcesor pola lecturer
    void setLecturer(Lecturer * lecturer);  // Mutator pola lecturer
    void addStudent(Student * student);  // Metoda dodająca studenta do wektora kursu
    void removeStudent(std::string login);  // Metoda usuwająca studenta z wektora kursu
    int getStudentsSize();  // Akcesor rozmiaru wektora studentów kursu
    Student * getStudentAtIndex(int studentIndex);  // Metoda zwracająca studenta z kursu o podanym indeksie
	void addMaterial(Material * material);  // Metoda dodająca materiał do wektora kursu
    void deleteMaterial(std::string name);  // Metoda usuwająca materiał z wektora kursu
	void createVideoConference(std::string name);  // Metoda tworząca wideokonferencję
	void endVideoConference();  // Metoda kończąca wideokonferencję
    void displayHeader(const std::string& headerName);  // Metoda wyświetlająca nagłówek
	void viewCoursePage();  // Metoda wyświetlająca stronę kursu
    void openStudentCourseMenu(Student * student);  // Metoda otwierająca menu kursu dla studenta
    void openLecturerCourseMenu(Lecturer * lecturer);  // Metoda otwierająca menu kursu dla wykładowcy
    void openMaterialsMenu(User * user);  // Metoda otwierająca menu materiałów
private:
	std::string name;  // Nazwa kursu
    Lecturer * lecturer;  // Wykładowca prowadzący kurs
    std::vector <Student *> students;  // Wektor studentów uczęszczających na kurs
	std::vector <Material *> materials;  // Wektor materiałów przypisanych do kursu
	VideoConference * videoConference;  // Wideokonferencja
};

#endif  //_COURSE_H
