//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Inżynieria Oprogramowania - Projekt
//  @ File Name : Kurs.cpp
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#include <iostream>
#include "Kurs.h"

Kurs::Kurs(std::string nazwa, Prowadzacy * prowadzacy) {
    this->nazwa = nazwa;
    this->prowadzacy = prowadzacy;
}

std::string Kurs::getNazwa() {
    return nazwa;
}

void Kurs::dodajUczestnika(Student * student) {
    uczestincy.push_back(student);
}

void Kurs::dodajMaterial(Material * material) {
    materialy.push_back(material);
}

void Kurs::utworzWideokonferencje(std::string nazwa) {
    this->nazwa = nazwa;
}

void Kurs::usunMaterial(std::string nazwa) {
    for(int i = 0; i < materialy.size(); i++) {
        if(materialy[i]->getNazwa() == nazwa) {
            materialy.erase(materialy.begin() + i);
        }
    }
}

void Kurs::zakonczWideokonferencje() {
    std::cout << "Zakonczono wideokonferencje\n";
    wideokonferencja = nullptr;
}

void Kurs::usunUczestnika(std::string login) {
    for(int i = 0; i < uczestincy.size(); i++) {
        if(uczestincy[i] == login) {
            uczestincy.erase(uczestincy.begin() + i);
        }
    }
}

