//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Inżynieria Oprogramowania - Projekt
//  @ File Name : Material.h
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#if !defined(_MATERIAL_H)
#define _MATERIAL_H

#include "Uzytkownik.h"
#include <string>

class Material {
public:
	Material(std::string nazwa, std::string data, int rozmiar, Uzytkownik* dodanyPrzez);
    std::string getNazwa();
    std::string getData();
	int getRozmiar();
	Uzytkownik* getDodanyPrzez();
private:
    std::string nazwa;
    std::string data;
	int rozmiar;
	Uzytkownik* dodanyPrzez;
};

#endif  //_MATERIAL_H
