//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Inżynieria Oprogramowania - Projekt
//  @ File Name : Material.cpp
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#include "Material.h"

Material::Material(std::string nazwa, std::string data, int rozmiar, Uzytkownik* dodanyPrzez) {
    this->nazwa = nazwa;
    this->data = data;
    this->rozmiar = rozmiar;
    this->dodanyPrzez = dodanyPrzez;
}

std::string Material::getNazwa() {
    return nazwa;
}

std::string Material::getData() {
    std::cout << "--"
}

int Material::getRozmiar() {

}

Uzytkownik* Material::getDodanyPrzez() {

}

