//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Inżynieria Oprogramowania - Projekt
//  @ File Name : Prowadzacy.cpp
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#include "Prowadzacy.h"

void Prowadzacy::dodajKurs(Kurs * kurs) {
    kursy.push_back(kurs);
}

void Prowadzacy::usunKurs(std::string nazwa) {
    for (int i = 0; i < kursy.size(); i++) {
        if (kursy[i]->getNazwa() == nazwa) {
            kursy.erase(kursy.begin() + i);
        }
    }
}
