//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Inżynieria Oprogramowania - Projekt
//  @ File Name : Student.h
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#if !defined(_STUDENT_H)
#define _STUDENT_H

#include <string>
#include <vector>
#include "Uzytkownik.h"
#include "Kurs.h"

class Kurs;
class Student : public Uzytkownik {
    using Uzytkownik::Uzytkownik;
public:
	void dodajKurs(Kurs *kurs);
	void usunKurs(std::string nazwa);
    Kurs * getKurs(int index);
    void printKursy();
private:
	std::vector <Kurs *> kursy;
};

#endif  //_STUDENT_H
