//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Inżynieria Oprogramowania - Projekt
//  @ File Name : Student.h
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#if !defined(_STUDENT_H)
#define _STUDENT_H

// Deklaracja zależności i bibliotek
#include <string>
#include <vector>
#include "User.h"
#include "Course.h"

// Deklaracja klas
class Course;

// Deklaracja klasy Student dziedziczącej po klasie User
class Student : public User {
    using User::User;  // Dziedziczenie konstruktorów klasy User
public:
	void addCourse(Course * course);  // Metoda dodająca kurs do wektora kursów
	void deleteCourse(std::string courseName);  // Metoda usuwająca kurs z wektora kursów
    Course * getCourseAtIndex(int courseIndex);  // Metoda zwracająca wskaźnik na kurs o podanym indeksie
    void printCourses();  // Metoda wyświetlająca courses
private:
	std::vector <Course *> courses;  // Wektor kursów
};

#endif  //_STUDENT_H
