//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : System Obsługi Studiów
//  @ File Name : System.h
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#if !defined(_SYSTEM_H)
#define _SYSTEM_H

// Deklaracja zależności i bibliotek
#include <string>
#include <vector>
#include "User.h"
#include "Course.h"

// Deklaracja klasy User
class System {
public:
	System(std::string name);  // Konstruktor klasy System
    std::string getName();  // Akcesor pola name
    bool authentication(User * user, std::string login, std::string password);  // Metoda autoryzująca użytkownika
	void login(User * user);  // Metoda logująca użytkownika
	void registerUser(User * user);  // Metoda rejestrująca użytkownika
    void deleteUser(std::string login);  // Metoda usuwająca użytkownika z wektora users
	void addCourse(Course * course);  // Metoda dodająca kurs do wektora kursów
    int getCoursesSize();  // Akcesor rozmiaru wektora kursów
    void printCourses();  // Metoda wyświetlająca kursy
	void deleteCourse(std::string courseName);  // Metoda usuwająca kurs z systemu
    void boot();  // Metoda uruchamiająca system
    void studentSystem();  // Metoda uruchamiająca system w wersji studenckiej
    void lecturerSystem();  // Metoda uruchamiająca system w werjsi wykładowcy
    void studentCourseMenu(Student * student);  // Metoda otwierająca menu kursów dla studenta
    void lecturerCourseMenu(Lecturer * lecturer);  // Metoda otwierająca menu kursów dla wykładowcy
    void loadUsersFromCSV(const std::string& fileName);  // Metoda wczytująca użytkowników z pliku CSV
    void saveUsersToCSV(const std::string& fileName);  // Metoda zapisująca użytkowników do pliku CSV
    void loadCoursesFromCSV(const std::string& fileName);  // Metoda wczytująca kursy z pliku CSV
    void saveCoursesToCSV(const std::string& fileName);  // Metoda zapisująca kursy do pliku CSV
private:
    std::string name;  // Nazwa systemu
    std::vector <Course *> courses;  // Wektor kursów
    std::vector <User *> users;  // Wektor użytkowników
};

#endif  //_SYSTEM_H
