//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Inżynieria Oprogramowania - Projekt
//  @ File Name : System.h
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#if !defined(_SYSTEM_H)
#define _SYSTEM_H

#include <string>
#include <vector>
#include "Uzytkownik.h"
#include "Kurs.h"

class System {
public:
	System(std::string nazwa);
    std::string getNazwa();
	void login(Uzytkownik * uzytkownik);
	void rejestracja(Uzytkownik * uzytkownik);
	void dodajKurs(Kurs * kurs);
	void usunKurs(std::string nazwa);
	void usunUzytkownika(std::string login);
    void printKursy();
	void printUzytkownik(Uzytkownik* uzytkownik);
    void boot();
    void bootStudent();
    void bootProwadzacy();
    void obslugaKursowStudenta(Student * student);
    void obslugaKursowProwadzacego(Prowadzacy * prowadzacy);
    void wczytajUzytkownikow(const std::string& fileName);
    void wczytajKursy(const std::string& fileName);
private:
    std::string nazwa;
    std::vector <Kurs*> kursy;
    std::vector <Uzytkownik*> uzytkownicy;
};

#endif  //_SYSTEM_H
