//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Inżynieria Oprogramowania - Projekt
//  @ File Name : User.h
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#if !defined(_USER_H)
#define _USER_H

// Deklaracja zależności i bibliotek
#include <iostream>
#include <string>

// Deklaracja klasy User
class User {
public:
	User(std::string firstName, std::string lastName, std::string login, std::string password, std::string email);  // Konstruktor klasy User z polami firstName, lastName, login, password i email
    User(std::string firstName, std::string lastName);  // Konstruktor klasy User z polami firstName i lastName
    User();  // Pusty konstruktor klasy User
	std::string getFirstName();  // Akcesor pola firstName
	void setFirstName(std::string firstName);  // Mutator pola firstName
	std::string getLastName();  // Akcesor pola lastName
	void setLastName(std::string lastName);  // Mutator pola lastName
	std::string getLogin();  // Akcesor pola login
	void setLogin(std::string login);  // Mutator pola login
	std::string getPassword();  // Akcesor pola password
	void setPassword(std::string password);  // Mutator pola password
	std::string getEmail();  // Akcesor pola email
	void setEmail(std::string email);  // Mutator pola email
	void printUser();  // Metoda wyświetlająca dane użytkownika
private:
	std::string firstName;  // Imię użytkownika
	std::string lastName;  // Nazwisko użytkownika
	std::string login;  // Login użytkownika
	std::string password;  // Hasło użytkownika
	std::string email;  // Adres email użytkownika
};

#endif  //_USER_H
