//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Inżynieria Oprogramowania - Projekt
//  @ File Name : Uzytkownik.cpp
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#include <iostream>
#include "Uzytkownik.h"

Uzytkownik::Uzytkownik(std::string imie, std::string nazwisko, std::string login, std::string haslo, std::string email) {
	this->imie = imie;
	this->nazwisko = nazwisko;
	this->login = login;
	this->haslo = haslo;
	this->email = email;
}

Uzytkownik::Uzytkownik(std::string imie, std::string nazwisko) {
    this->imie = imie;
    this->nazwisko = nazwisko;
}

void Uzytkownik::setImie(std::string imie) {
	this->imie = imie;
}

std::string Uzytkownik::getImie() {
    return imie;
}

std::string Uzytkownik::getNazwisko() {
	return nazwisko;
}

void Uzytkownik::setNazwisko(std::string nazwisko) {
	this->nazwisko = nazwisko;
}

std::string Uzytkownik::getLogin() {
	return login;
}

void Uzytkownik::setLogin(std::string login) {
	this->login = login;
}

std::string Uzytkownik::getHaslo() {
	return haslo;
}

void Uzytkownik::setHaslo(std::string haslo) {
	this->haslo = haslo;
}

std::string Uzytkownik::getEmail() {
	return email;
}

void Uzytkownik::setEmail(std::string email) {
	this->email = email;
}

void Uzytkownik::printUzytkownik() {
	std::cout << imie << " " << nazwisko << "\n";
}
