//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Inżynieria Oprogramowania - Projekt
//  @ File Name : VideoConference.cpp
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

// Deklaracja zależności i bibliotek
#include "VideoConference.h"

// Konstruktor
VideoConference::VideoConference(std::string name, Lecturer * lecturer) {
	this->name = name;
	this->lecturer = lecturer;
}

// Metoda dodająca studenta do konferencji
void VideoConference::addStudent(Student * student) {
    // Dodanie studenta do wektora studentów
	students.push_back(student);
}

// Metoda usuwająca studenta z konferencji
void VideoConference::deleteStudent(std::string login) {
    // Przeszukaje wektor studentów
	for(int i = 0; i < students.size(); i++) {
        // Jeżeli login studenta jest równy podanemu loginowi
		if(students[i]->getLogin() == login) {
            // Usuń studenta z wektora
			students.erase(students.begin() + i);
            // Zakończ pętlę
			break;
		}
	}
}

// Metoda wyświetlająca nagłówek
void VideoConference::displayHeader(const std::string& name) {
    const int totalWidth = 90;  // Szerokość całego wyświetlanego napisu
    const int nameWidth = name.length();  // Szerokość nazwy kursu
    const int paddingWidth = (totalWidth - nameWidth) / 2;  // Szerokość wypełnienia
    // Wyświetl nagłówek
    std::cout << "==========================================================================================\n";
    std::cout << std::string(paddingWidth, ' ') << name << "\n";;
    std::cout << "==========================================================================================\n";
}

// Metoda otwierająca menu konferencji dla studenta
void VideoConference::openStudentVideoConferenceMenu(Student * student) {
    // Utwórz zmienną przechowującą wybór użytkownika
    std::string userInput;

    // Pętla menu wideokonferencji studenta
	while(true) {
        // Wyświetl nagłówek menu wideokonferencji studenta
        displayHeader("Wideokonferencja - " + name);

        // Wyświetl opcje
		std::cout << "Wybierz opcje:" << "\n";
		std::cout << "1. Wyswietl uczestnikow" << "\n";
		std::cout << "2. Wyjdz" << "\n";

        // Pobierz wybór użytkownika
		std::cin >> userInput;

        // Wykonaj akcję w zależności od wyboru użytkownika
        // Jeżeli wybór to 1
		if(userInput == "1") {
            // Wyświetl nagłówek uczestników wideokonferencji
            displayHeader("Uczestnicy Wideokonferencji - " + name);

            // Wyświetl wykładowcę
            std::cout << "Wykladowca: " << lecturer->getFirstName() << " " << lecturer->getLastName() << "\n";

            // Jeżeli wektor studentów nie jest pusty
            if(!students.empty()) {
                // Przeszukaj wektor studentów
                for(int i = 0; i < students.size(); i++) {
                    // Wyświetl imiona i nazwiska studentów w wideokonferencji
                    std::cout << i + 1 << ". " << students.at(i)->getFirstName() << " " << students.at(i)->getLastName() << "\n";
                }
            } else {
                // Wyświetl komunikat o braku uczestników
                std::cout << "Brak uczestnikow!" << "\n";
            }
        // Jeżeli wybór to 2
		} else if(userInput == "2") {
            // Przeszukaj wektor studentów
			for(int i = 0; i < students.size(); i++) {
                // Jeżeli student jest równy studentowi z wektora
				if(students[i] == student) {
                    // Usuń studenta z wektora
                    deleteStudent(student->getLogin());
                    // Wyświetl komunikat o wyjściu z wideokonferencji
                    std::cout << "Wyjscie z wideokonferencji!" << "\n";
                    // Zakończ pętlę
					break;
				}
			}
            // Wyjdź z wideokonferencji
            break;
        // W przeciwnym wypadku
		} else {
            // Wyświetl komunikat o niepoprawnym wyborze
            std::cout << "Niepoprawna opcja!" << "\n";
		}
	}
}

// Metoda otwierająca menu konferencji dla wykładowcy
void VideoConference::openLecturerVideoConferenceMenu(Lecturer * lecturer) {
    // Utwórz zmienną przechowującą wybór użytkownika
    std::string userInput;

    // Pętla menu wideokonferencji wykładowcy
    while(true) {
        // Wyświetl nagłówek menu wideokonferencji wykładowcy
        displayHeader("Wideokonferencja - " + name);

        // Wyświetl opcje
        std::cout << "Wybierz opcje:" << "\n";
        std::cout << "1. Wyswietl uczestnikow" << "\n";
        std::cout << "2. Zakoncz wideokonferencje" << "\n";

        // Pobierz wybór użytkownika
        std::cin >> userInput;

        // Wykonaj akcję w zależności od wyboru użytkownika
        // Jeżeli wybór to 1
        if(userInput == "1") {
            // Wyświetl nagłówek uczestników wideokonferencji
            displayHeader("Uczestnicy Wideokonferencji - " + name);

            // Wyświetl wykładowcę
            std::cout << "Wykladowca: " << lecturer->getFirstName() << " " << lecturer->getLastName() << "\n";

            // Jeżeli wektor studentów nie jest pusty
            if(!students.empty()) {
                // Przeszukaj wektor studentów
                for(int i = 0; i < students.size(); i++) {
                    // Wyświetl imiona i nazwiska studentów w wideokonferencji
                    std::cout << i + 1 << ". " << students.at(i)->getFirstName() << " " << students.at(i)->getLastName() << "\n";
                }
            } else {
                // Wyświetl komunikat o braku uczestników
                std::cout << "Brak uczestnikow!" << "\n";
            }
            // Jeżeli wybór to 2
        } else if(userInput == "2") {
            // Przeszukaj wektor studentów
            for(int i = 0; i < students.size(); i++) {
                // Usuń studenta z wektora studentów po zakończeniu wideokonferencji
                deleteStudent(students[i]->getLogin());
            }
            // Wyświetl komunikat o zakończeniu wideokonferencji
            std::cout << "Zakonczono wideokonferencje!" << "\n";
            // Wyjdź z wideokonferencji
            break;
        } else {
            // Wyświetl komunikat o niepoprawnym wyborze
            std::cout << "Niepoprawna opcja!" << "\n";
        }
    }
}

