//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Inżynieria Oprogramowania - Projekt
//  @ File Name : Wideokonferencja.cpp
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#include "Wideokonferencja.h"

Wideokonferencja::Wideokonferencja(std::string nazwa, Prowadzacy *prowadzacy) {
	this->nazwa = nazwa;
	this->prowadzacy = prowadzacy;
}

void Wideokonferencja::dodajUczestnika(Student *student) {
	uczestnicy.push_back(student);
}

void Wideokonferencja::usunUczestnika(std::string login) {
	for (int i = 0; i < uczestnicy.size(); i++) {
		if (uczestnicy[i]->getLogin() == login) {
			uczestnicy.erase(uczestnicy.begin() + i);
			break;
		}
	}
}

void Wideokonferencja::otworzMenu(Uzytkownik *uzytkownik) {
	while (true) {
		std::string userInput;
		std::cout << "Wideokonferencja: " << this->nazwa << "\n";
		std::cout << "Wybierz opcje:\n";
		std::cout << "1. Wyswietl uczestnikow\n";
		std::cout << "2. Wyjdz\n";
		std::cin >> userInput;
		if (userInput == "1") {
			for (int i = 0; i < uczestnicy.size(); i++) {
				std::cout << uczestnicy.at(i)->getImie() << " " <<
					uczestnicy.at(i)->getNazwisko() << "\n";
			}
		} else if (userInput == "2") {
			for (int i = 0; i < uczestnicy.size(); i++) {
				if (uczestnicy[i] == uzytkownik) {
					uczestnicy.erase(uczestnicy.begin() + i);
					break;
				}
			}
			break;
		}
	}
}
