//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Inżynieria Oprogramowania - Projekt
//  @ File Name : Wideokonferencja.h
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#if !defined(_WIDEOKONFERENCJA_H)
#define _WIDEOKONFERENCJA_H

#include <iostream>
#include <string>
#include <vector>
#include "Prowadzacy.h"
#include "Student.h"

class Prowadzacy;
class Student;
class Wideokonferencja {
public:
	Wideokonferencja(std::string nazwa, Prowadzacy *prowadzacy);
	void dodajUczestnika(Student *student);
	void usunUczestnika(std::string login);
	void otworzMenuStudenta(Uzytkownik *uzytkownik);
	void otworzMenuProwadzacego(Uzytkownik *uzytkownik);
private:
	std::string nazwa;
	Prowadzacy * prowadzacy;
	std::vector <Student *> uczestnicy;
};

#endif  //_WIDEOKONFERENCJA_H
