//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Inżynieria Oprogramowania - Projekt
//  @ File Name : Wideokonferencja.h
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#if !defined(_WIDEOKONFERENCJA_H)
#define _WIDEOKONFERENCJA_H

#include <string>
#include <vector>
#include "Prowadzacy.h"
#include "Student.h"

class Wideokonferencja {
public:
	Wideokonferencja(std::string nazwa, Prowadzacy* prowadzacy);
    void dodajUczestnika(Student * student);
	void usunUczestnika(std::string login);
private:
    std::string nazwa;
	Prowadzacy* prowadzacy;
    std::vector <Student *> uczestnicy;
};

#endif  //_WIDEOKONFERENCJA_H
