//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : System Obsługi Studiów
//  @ File Name : Lecturer.cpp
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#include "Lecturer.h"

void Lecturer::addCourse(Course * course) {
    courses.push_back(course);
}

void Lecturer::removeCourse(std::string courseName) {
    for (int i = 0; i < courses.size(); i++) {
        if (courses[i]->getName() == courseName) {
            courses.erase(courses.begin() + i);
        }
    }
}

int Lecturer::getCoursesSize() {
    return courses.size();
}

Course * Lecturer::getCourseAtIndex(int courseIndex) {
    return courses[courseIndex];
}

void Lecturer::printCourses() {
    std::cout << "[========================================================================================]\n";
    std::cout << "|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Twoje Kursy~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|\n";
    std::cout << "[========================================================================================]\n";
    for (int i = 0; i < courses.size(); i++) {
        std::cout << "| " << i + 1 << ". " << courses[i]->getName() << "\n";
    }
}
