//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : System Obsługi Studiów
//  @ File Name : Lecturer.h
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
// 

#if !defined(_LECTURER_H)
#define _LECTURER_H

#include <string>
#include <vector>

#include "User.h"
#include "Course.h"

class Course;

/**
 * Klasa wykładowcy
 */
class Lecturer : public User {
	using User::User;
public:

	/*
	 * Dodaje kurs do wektora kursów wykładowcy
	 *
	 * @param course Kurs
	 */
	void addCourse(Course * course);

	/*
	 * Usuwa kurs z wektora kursów wykładowcy
	 *
	 * @param courseName Nazwa kursu
	 */
	void removeCourse(std::string courseName);

	/*
	 * Zwraca rozmiar wektora kursów wykładowcy
	 *
	 * @return Rozmiar wektora kursów wykładowcy
	 */
    int getCoursesSize();

	/*
	 * Zwraca kurs z wektora kursów wykładowcy o podanym indeksie
	 *
	 * @param courseIndex Indeks kursu
	 *
	 * @return Kurs
	 */
    Course * getCourseAtIndex(int courseIndex);

	/*
	 * Wyświetla kursy wykładowcy
	 */
    void printCourses();

private:

	/**
	 * Wektor kursów wykładowcy
	 */
	std::vector <Course *> courses;
};

#endif  //_LECTURER_H
