//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : System Obsługi Studiów
//  @ File Name : Material.cpp
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#include "Material.h"

Material::Material(std::string name, std::string description, std::string fileName, int fileSize, User *addedBy) {
	this->name = name;
	this->description = description;
	this->fileName = fileName;
	this->fileSize = fileSize;
	this->addedBy = addedBy;
}

std::string Material::getName() {
	return name;
}

void Material::setName(std::string name) {
    this->name = name;
}

std::string Material::getDescription() {
    return description;
}

void Material::setDescription(std::string description) {
    this->description = description;
}

std::string Material::getFileName() {
    return fileName;
}

void Material::setFileName(std::string fileName) {
    this->fileName = fileName;
}

int Material::getFileSize() {
    return fileSize;
}

void Material::setFileSize(int fileSize) {
    this->fileSize = fileSize;
}

User * Material::getAddedBy() {
    return addedBy;
}

void Material::setAddedBy(User * addedBy) {
    this->addedBy = addedBy;
}

void Material::printMaterial() {
    std::cout << "[========================================================================================]\n";
    std::cout << "|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Dane Materialu~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|\n";
    std::cout << "|========================================================================================|\n";
    std::cout << "| Nazwa: " << this->name << "\n";
    std::cout << "| Opis: " << this->description << "\n";
    std::cout << "| Nazwa pliku: " << this->fileName << "\n";
    std::cout << "| Rozmiar pliku: " << this->fileSize << "\n";
    std::cout << "| Dodany przez: " << this->addedBy->getFirstName() << "\n";
    std::cout << "[========================================================================================]\n";
}

void Material::materialsMenu() {
    std::string userInput;

	while (true) {
        std::cout << "[========================================================================================]\n";
        std::cout << "|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Menu Materialu~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|\n";
        std::cout << "[========================================================================================]\n";
        std::cout << "| 1. Wyswietl dane                                                                       |\n";
        std::cout << "| 2. Pobierz plik                                                                        |\n";
        std::cout << "| 3. Wroc                                                                                |\n";
        std::cout << "[========================================================================================]\n";

        std::cin >> userInput;
        switch (std::stoi(userInput)) {
            case 1:
                printMaterial();
                break;
            case 2:
                downloadFile();
                break;
            case 3:
                return;
            default:
                std::cout << "Niepoprawna opcja!" << "\n";
                break;
        }
	}
}

void Material::downloadFile() {
	int barWidth = 88;
	int duration = 100;
	int total = 10;

	for (int i = 0; i < total; i++) {
		std::cout << "[";
		int progress = (barWidth * i) / total;
		for (int j = 0; j < barWidth; j++) {
			if (j < progress) {
				std::cout << "=";
			} else if (j == progress) {
				std::cout << ">";
			} else {
				std::cout << " ";
			}
		}
		std::cout << "] " << int((float(i) / total) * 100.0) << "%\r";
		std::cout.flush();
		std::this_thread::sleep_for(std::chrono::milliseconds(duration));
	}

    std::cout << "[";
    for (int j = 0; j < barWidth; ++j) {
        std::cout << "=";
    }
    std::cout << "] 100%" << std::endl;
    std::cout << "Pobrano plik!" << std::endl;
}
