//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : System Obsługi Studiów
//  @ File Name : Material.h
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#if !defined(_MATERIAL_H)
#define _MATERIAL_H

#include <string>
#include <iostream>
#include <thread>
#include <chrono>

#include "User.h"

/**
 * Klasa materiału kursu uniwersyteckiego
 */
class Material {
public:

    /**
     * Konstruktor
     *
     * @param name Nazwa materiału
     * @param description Opis materiału
     * @param fileName Nazwa pliku
     * @param fileSize Rozmiar pliku
     * @param addedBy Użytkownik dodający materiał
     */
	Material(std::string name, std::string description, std::string fileName, int fileSize, User * addedBy);

    /**
     * Zwraca nazwę materiału
     *
     * @return Nazwa materiału
     */
	std::string getName();

    /**
     * Ustawia nazwę materiału
     *
     * @param name Nazwa materiału
     */
    void setName(std::string name);

    /**
     * Zwraca opis materiału
     *
     * @return Opis materiału
     */
    std::string getDescription();

    /**
     * Ustawia opis materiału
     *
     * @param description Opis materiału
     */
    void setDescription(std::string description);

    /**
     * Zwraca nazwę pliku
     *
     * @return Nazwa pliku
     */
    std::string getFileName();

    /**
     * Ustawia nazwę pliku
     *
     * @param fileName Nazwa pliku
     */
    void setFileName(std::string fileName);

    /**
     * Zwraca rozmiar pliku
     *
     * @return Rozmiar pliku
     */
    int getFileSize();

    /**
     * Ustawia rozmiar pliku
     *
     * @param fileSize Rozmiar pliku
     */
    void setFileSize(int fileSize);

    /**
     * Zwraca użytkownika dodającego materiał
     *
     * @return Użytkownik dodający materiał
     */
    User * getAddedBy();

    /**
     * Ustawia użytkownika dodającego materiał
     *
     * @param addedBy Użytkownik dodający materiał
     */
    void setAddedBy(User * addedBy);

    /**
     * Wyświetla informacje o materiale
     */
	void printMaterial();

    /**
     * Otwiera menu materiału
     */
	void materialsMenu();

    /**
     * Pobiera plik
     */
	void downloadFile();

private:

    /**
     * Nazwa materiału
     */
	std::string name;

    /**
     * Opis materiału
     */
    std::string description;

    /**
     * Nazwa pliku
     */
    std::string fileName;

    /**
     * Rozmiar pliku
     */
	int fileSize;

    /**
     * Użytkownik dodający materiał
     */
	User * addedBy;
};

#endif  //_MATERIAL_H
