//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : System Obsługi Studiów
//  @ File Name : Student.cpp
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#include "Student.h"

void Student::addCourse(Course * course) {
	courses.push_back(course);
}

void Student::removeCourse(std::string courseName) {
	for (int i = 0; i < courses.size(); i++) {
		if (courses[i]->getName() == courseName) {
			courses.erase(courses.begin() + i);
		}
	}
}

int Student::getCoursesSize() {
    return courses.size();
}

Course * Student::getCourseAtIndex(int courseIndex) {
    return courses[courseIndex];
}

void Student::printCourses() {
    std::cout << "[========================================================================================]\n";
    std::cout << "|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Twoje Kursy~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|\n";
    std::cout << "[========================================================================================]\n";
    for (int i = 0; i < courses.size(); i++) {
        std::cout << "| " << i + 1 << ". " << courses[i]->getName() << "\n";
    }
}
