//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : System Obsługi Studiów
//  @ File Name : User.cpp
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#include <iostream>

#include "User.h"

User::User(std::string firstName, std::string lastName, std::string login, std::string password, std::string email) {
	this->firstName = firstName;
	this->lastName = lastName;
	this->login = login;
	this->password = password;
	this->email = email;
}

User::User(std::string firstName, std::string lastName) {
    this->firstName = firstName;
    this->lastName = lastName;
}

User::User() {}

std::string User::getFirstName() {
    return firstName;
}

void User::setFirstName(std::string firstName) {
	this->firstName = firstName;
}

std::string User::getLastName() {
	return lastName;
}

void User::setLastName(std::string lastName) {
	this->lastName = lastName;
}

std::string User::getLogin() {
	return login;
}

void User::setLogin(std::string login) {
	this->login = login;
}

std::string User::getPassword() {
	return password;
}

void User::setPassword(std::string password) {
	this->password = password;
}

std::string User::getEmail() {
	return email;
}

void User::setEmail(std::string email) {
	this->email = email;
}

void User::printUser() {
    const std::string headerName = "Uzytkownik";
    const int totalWidth = 90;
    const int nameWidth = headerName.length();
    const int paddingWidth = (totalWidth - nameWidth) / 2;

    std::string hiddenUserPassword = getPassword();
    hiddenUserPassword.replace(0, hiddenUserPassword.length(), hiddenUserPassword.length(), '*');
    std::cout << "[========================================================================================]\n";
    std::cout << "|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Uzytkownik~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|\n";
    std::cout << "|========================================================================================|\n";
    std::cout << "| Login: " << getLogin() << "\n";
    std::cout << "| Haslo: " << hiddenUserPassword << "\n";
    std::cout << "| Imie: " << getFirstName() << "\n";
    std::cout << "| Nazwisko: " << getLastName() << "\n";
    std::cout << "| Email: " << getEmail() << "\n";
    std::cout << "[========================================================================================]\n";
}
