//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : System Obsługi Studiów
//  @ File Name : User.h
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#if !defined(_USER_H)
#define _USER_H

#include <iostream>
#include <string>

/**
 * Klasa użytkownika
 */
class User {
public:

	/**
	 * Konstruktor klasy User z polami firstName, lastName, login, password i email
	 *
	 * @param firstName Imię użytkownika
	 * @param lastName Nazwisko użytkownika
	 * @param login Login użytkownika
	 * @param password Hasło użytkownika
	 * @param email Adres email użytkownika
	 */
	User(std::string firstName, std::string lastName, std::string login, std::string password, std::string email);

	/**
	 * Konstruktor klasy User z polami firstName i lastName
	 *
	 * @param firstName Imię użytkownika
	 * @param lastName Nazwisko użytkownika
	 */
	User(std::string firstName, std::string lastName);

	/**
	 * Pusty konstruktor klasy User
	 */
	User();

	/**
	 * Akcesor pola firstName
	 *
	 * @return Imię użytkownika
	 */
	std::string getFirstName();

	/**
	 * Mutator pola firstName
	 *
	 * @param firstName Imię użytkownika
	 */
	void setFirstName(std::string firstName);

	/**
	 * Akcesor pola lastName
	 *
	 * @return Nazwisko użytkownika
	 */
	std::string getLastName();

	/**
	 * Mutator pola lastName
	 *
	 * @param lastName Nazwisko użytkownika
	 */
	void setLastName(std::string lastName);

	/**
	 * Akcesor pola login
	 *
	 * @return Login użytkownika
	 */
	std::string getLogin();

	/**
	 * Mutator pola login
	 *
	 * @param login Login użytkownika
	 */
	void setLogin(std::string login);

	/**
	 * Akcesor pola password
	 *
	 * @return Hasło użytkownika
	 */
	std::string getPassword();

	/**
	 * Mutator pola password
	 *
	 * @param password Hasło użytkownika
	 */
	void setPassword(std::string password);

	/**
	 * Akcesor pola email
	 *
	 * @return Adres email użytkownika
	 */
	std::string getEmail();

	/**
	 * Mutator pola email
	 *
	 * @param email Adres email użytkownika
	 */
	void setEmail(std::string email);

	/**
	 * Metoda wyświetlająca dane użytkownika
	 */
	void printUser();

private:

	/**
	 * Imię użytkownika
	 */
	std::string firstName;

	/**
	 * Nazwisko użytkownika
	 */
	std::string lastName;

	/**
	 * Login użytkownika
	 */
	std::string login;

	/**
	 * Hasło użytkownika
	 */
	std::string password;

	/**
	 * Adres email użytkownika
	 */
	std::string email;
};

#endif  //_USER_H
