//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : System Obsługi Studiów
//  @ File Name : VideoConference.h
//  @ Date : 10.06.2023
//  @ Author : Tomasz Wnuk, Bartosz Szynkaruk, Mikołaj Hasiec
//
//

#if !defined(_VIDEOCONFERENCE_H)
#define _VIDEOCONFERENCE_H

#include <iostream>
#include <string>
#include <vector>

#include "Lecturer.h"
#include "Student.h"

class Lecturer;
class Student;

/**
 * Klasa wideokonferencji
 */
class VideoConference {
public:

	/**
	 * Konstruktor
	 *
	 * @param name Nazwa wideokonferencji
	 * @param lecturer Wykładowca prowadzący wideokonferencję
	 */
	VideoConference(std::string name, Lecturer * lecturer);

	/**
	 * Zwraca nazwę wideokonferencji
	 *
	 * @return Nazwa wideokonferencji
	 */
	void addStudent(Student * student);

	/**
	 * Zwraca nazwę wideokonferencji
	 *
	 * @return Nazwa wideokonferencji
	 */
	void removeStudent(std::string login);

	/**
	 * Otwiera menu wideokonferencji dla studenta
	 */
	void openStudentVideoConferenceMenu(Student * student);

	/**
	 * Otwiera menu wideokonferencji dla wykładowcy
	 */
	void openLecturerVideoConferenceMenu(Lecturer * lecturer);

private:

	/**
	 * Nazwa wideokonferencji
	 */
	std::string name;

	/**
	 * Wykładowca prowadzący wideokonferencję
	 */
	Lecturer * lecturer;

	/**
	 * Wektor studentów uczestniczących w wideokonferencji
	 */
	std::vector <Student *> students;
};

#endif  //_VIDEOCONFERENCE_H
